import { createHash } from "node:crypto";
import type { SerializedColumn } from "../../migration/serialized/serializedColumn.js";
import type { SerializedTable } from "../../migration/serialized/serializedStore.js";
import { getSqlString } from "../../runtime/sql/sqlString.js";

const SqlString = getSqlString("postgres");

export function postgresType(
  column: Pick<SerializedColumn, "type" | "length" | "scale">,
): string {
  const sized = () =>
    column.length === undefined
      ? ""
      : `(${[column.length, column.scale].filter((v) => v !== undefined).join(",")})`;
  switch (column.type) {
    case "tinyint":
    case "smallint":
    case "year":
      return "smallint";
    case "mediumint":
    case "int":
      return "integer";
    case "bigint":
      return "bigint";
    case "float":
      return "real";
    case "double":
      return "double precision";
    case "decimal":
      return "numeric" + sized();
    case "datetime":
    case "timestamp":
      return "timestamp without time zone";
    case "varchar":
    case "char":
      return column.type + sized();
    default:
      return column.type;
  }
}

export function postgresColumn(column: SerializedColumn): string {
  const name = SqlString.escapeId(column.columnName);
  if (column.zerofill)
    throw new Error("PostgreSQL does not support ZEROFILL columns");
  const type = postgresType(column);
  if (
    column.autoIncrement &&
    !["smallint", "integer", "bigint"].includes(type)
  ) {
    throw new Error("PostgreSQL identity requires an integer column");
  }
  const words = [name, type];
  if (column.autoIncrement) words.push("GENERATED BY DEFAULT AS IDENTITY");
  if (column.notNull) words.push("NOT NULL");
  if (column.default !== undefined && !column.autoIncrement) {
    words.push(
      "DEFAULT " +
        (column.defaultCurrentTimeStamp ||
        (["datetime", "timestamp"].includes(column.type) &&
          column.default === "CURRENT_TIMESTAMP")
          ? "CURRENT_TIMESTAMP"
          : SqlString.escape(column.default)),
    );
  }
  if (column.signed === false) words.push(`CHECK (${name} >= 0)`);
  return words.join(" ");
}

function timestampFunction(table: string) {
  return (
    "sasat_updated_" +
    createHash("sha256").update(table).digest("hex").slice(0, 20)
  );
}

/** Implement the migration API's ON UPDATE timestamp option using a trigger. */
export function postgresTimestampTrigger(table: SerializedTable): string[] {
  const columns = table.columns.filter((c) => c.onUpdateCurrentTimeStamp);
  if (!columns.length) return [];
  const q = SqlString.escapeId;
  const body = `BEGIN IF NEW IS DISTINCT FROM OLD THEN ${columns
    .map((c) => {
      const col = q(c.columnName);
      return `IF NEW.${col} IS NOT DISTINCT FROM OLD.${col} THEN NEW.${col} := CURRENT_TIMESTAMP; END IF;`;
    })
    .join(" ")} END IF; RETURN NEW; END`;
  const fn = q(timestampFunction(table.tableName));
  return [
    `CREATE OR REPLACE FUNCTION ${fn}() RETURNS trigger LANGUAGE plpgsql AS ${SqlString.escape(body)}`,
    `DROP TRIGGER IF EXISTS "sasat_update_timestamp" ON ${q(table.tableName)}`,
    `CREATE TRIGGER "sasat_update_timestamp" BEFORE UPDATE ON ${q(table.tableName)} FOR EACH ROW EXECUTE FUNCTION ${fn}()`,
  ];
}

export function dropPostgresTimestampFunction(table: string): string {
  return `DROP FUNCTION IF EXISTS ${SqlString.escapeId(timestampFunction(table))}()`;
}
