extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - "@typescript-eslint"
env:
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType": module
rules:
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/no-non-null-assertion": 0
  "@typescript-eslint/ban-ts-ignore": 0
  prettier/prettier: 1

