db:
  host: $DB_HOST
  port: $DB_PORT
  user: $DB_USER
  password: $DB_PASSWORD
  database: $DATABASE

redis:
  host: $REDIS_HOST
  port: $REDIS_PORT
  password: $REDIS_PASSWORD

cache:
  name1:
    type: string
    table: user
    key: id
    value: name
  name2:
    type: JSON
    table: test
    key: id
    values:
      - c1
      - c2
  name3:
    type: hash
    table: test
    key: id
    values:
      - c1
      - c2


#hash:
migration:
  dir: ./migrations



