import { config, setConfig } from "../config/config.js";
import { StoreMigrator } from "../migration/front/storeMigrator.js";
import { QExpr } from "../runtime/dsl/factory.js";
import { queryToSql } from "../runtime/dsl/query/sql/queryToSql.js";
import { SqlString } from "../runtime/sql/sqlString.js";
import { formatQuery } from "./formatQuery.js";
import { createSqlGenerator } from "./sqlGenerator.js";

const postgres = createSqlGenerator("postgres");
const mysql = createSqlGenerator("mysql");
const originalDialect = config().db.dialect ?? "mysql";
afterEach(() => setConfig({ db: { dialect: originalDialect } }));
const tableInfo = {
  users: {
    identifiableKeys: ["user_id"],
    identifiableFields: ["id"],
    columnMap: { id: "user_id", name: "displayName" },
  },
};

test("keeps immutable generators independent of global configuration and concurrent work", async () => {
  setConfig({ db: { dialect: "mysql" } });
  const results = await Promise.all([
    (async () => {
      await Promise.resolve();
      return postgres.escapeId("a");
    })(),
    (async () => {
      setConfig({ db: { dialect: "postgres" } });
      return mysql.escapeId("a");
    })(),
  ]);
  expect(results).toEqual(['"a"', "`a`"]);
  expect(createSqlGenerator()).toBe(postgres);
  expect(Object.isFrozen(postgres)).toBe(true);
  expect(Object.isFrozen(postgres.nodes)).toBe(true);
});

test("escapes PostgreSQL values without MySQL backslash semantics", () => {
  expect(postgres.escape("O'Reilly\\'; DROP TABLE users; --")).toBe(
    "E'O''Reilly\\\\''; DROP TABLE users; --'",
  );
  expect(postgres.escapeId('schema.Mixed"Case')).toBe('"schema"."Mixed""Case"');
  expect(postgres.escape(false)).toBe("FALSE");
  expect(postgres.escape(null)).toBe("NULL");
  expect(() => postgres.escape("a\0b")).toThrow("NUL");
  expect(() => postgres.escape(Infinity)).toThrow("finite");
});

test("generates identity, quoted constraints, indexes, alterations and timestamp triggers", () => {
  const store = StoreMigrator.deserialize({ tables: [] }, postgres);
  store.createTable("users", (t) => {
    t.autoIncrementHashId("userId");
    t.column("name").varchar(40).unique();
    t.updatedAt();
    t.addIndex("name");
  });
  const sql = store.getSql().join(";\n");
  expect(sql).toContain('"userId" integer GENERATED BY DEFAULT AS IDENTITY');
  expect(sql).toContain('CHECK ("userId" >= 0)');
  expect(sql).toContain('UNIQUE ("name")');
  expect(sql).toContain('CREATE INDEX "index_users__name"');
  expect(sql).toContain('CREATE TRIGGER "sasat_update_timestamp"');
  expect(sql).not.toMatch(
    /AUTO_INCREMENT|UNSIGNED|ON UPDATE CURRENT_TIMESTAMP/,
  );
  store.resetQueue();
  store
    .table("users")
    .changeColumnType("name", "text")
    .setDefault("name", "guest")
    .removeIndex("name");
  expect(store.getSql()).toEqual([
    'ALTER TABLE "users" ALTER COLUMN "name" TYPE text',
    'ALTER TABLE "users" ALTER "name" SET DEFAULT E\'guest\'',
    'DROP INDEX "index_users__name"',
  ]);
});

test("uses RETURNING, DEFAULT VALUES and explicit PostgreSQL conflict targets", () => {
  expect(
    postgres.create(
      { table: "users", fields: [], entities: [[]], returning: "user_id" },
      tableInfo,
    ),
  ).toBe(
    'INSERT INTO "users" DEFAULT VALUES RETURNING "user_id" AS "__sasat_insert_id"',
  );
  const sql = postgres.create(
    {
      table: "users",
      fields: ["id", "name"],
      entities: [[1, "Ada"]],
      upsert: ["displayName"],
      returning: "user_id",
    },
    tableInfo,
  );
  expect(sql).toContain(
    'ON CONFLICT ("user_id") DO UPDATE SET "displayName" = EXCLUDED."displayName"',
  );
  expect(
    postgres.create(
      { table: "users", fields: ["name"], entities: [["Ada"]], ignore: true },
      tableInfo,
    ),
  ).toContain("ON CONFLICT DO NOTHING");
  expect(
    postgres.create(
      {
        table: "users",
        fields: ["name"],
        entities: [["Ada"]],
        upsert: ["displayName"],
        conflictColumns: ["displayName"],
      },
      tableInfo,
    ),
  ).toContain('ON CONFLICT ("displayName")');
});

test("quotes SQL aliases and preserves conditions, zero limits and root-only row locks", () => {
  const field = QExpr.field("u", "userId");
  const query = {
    select: [field],
    from: QExpr.table("users", [], "u"),
    where: QExpr.eq(field, QExpr.value(1)),
    limit: 0,
    lock: "FOR UPDATE" as const,
  };
  expect(postgres.query(query)).toBe(
    'SELECT "u"."userId" FROM "users" AS "u" WHERE "u"."userId"  = 1 LIMIT 0 FOR UPDATE OF "u"',
  );
});

test("passes one generator through nested FROM, EXISTS and IN queries", () => {
  const nested = {
    select: [QExpr.field("users", "user_id")],
    from: QExpr.table("users", [], "users"),
    where: QExpr.eq(QExpr.field("users", "name"), QExpr.value("Ada")),
  };
  const query = {
    select: [QExpr.field("u", "user_id")],
    from: {
      ...QExpr.table("users", [], "u"),
      subquery: true as const,
      query: nested,
    },
    where: QExpr.and(
      QExpr.exists(nested),
      QExpr.in(QExpr.field("u", "user_id"), nested),
    ),
  };
  for (const [generator, opposite, quote] of [
    [postgres, "mysql", '"'],
    [mysql, "postgres", "`"],
  ] as const) {
    setConfig({ db: { dialect: opposite } });
    const sql = generator.query(query);
    expect(sql).toContain("EXISTS (SELECT " + quote);
    expect(sql).toContain("IN (SELECT " + quote);
    expect(sql).toContain("FROM (SELECT " + quote);
    expect(sql).toContain(generator.escape("Ada"));
    expect(sql).not.toContain(opposite === "mysql" ? "`" : '"');
  }
});

test("migration stores keep their generator through config changes and deserialization", () => {
  for (const generator of [postgres, mysql]) {
    const store = StoreMigrator.deserialize({ tables: [] }, generator);
    setConfig({
      db: { dialect: generator.dialect === "postgres" ? "mysql" : "postgres" },
    });
    store.createTable("items", (t) => {
      t.autoIncrementHashId("id");
      t.updatedAt();
    });
    const restored = StoreMigrator.deserialize(store.serialize(), generator);
    expect(restored.table("items").column("id").toSql()).toBe(
      store.table("items").column("id").toSql(),
    );
    expect(restored.table("items").showCreateTable()).toBe(store.getSql()[0]);
    restored.table("items").dropColumn("updatedAt");
    restored.dropTable("items");
    const sql = restored.getSql().join(";");
    if (generator.dialect === "postgres") {
      expect(sql).toContain('ALTER TABLE "items" DROP COLUMN "updatedAt"');
      expect(sql).toContain("DROP FUNCTION IF EXISTS");
      expect(sql).not.toContain("`");
    } else {
      expect(sql).toContain("ALTER TABLE items DROP COLUMN updatedAt");
      expect(sql).not.toContain("DROP FUNCTION");
    }
  }
});

test("public convenience helpers use config while explicit generators override it", () => {
  const query = {
    select: [QExpr.field("users", "id")],
    from: QExpr.table("users", [], "users"),
  };
  for (const generator of [mysql, postgres]) {
    setConfig({ db: { dialect: generator.dialect } });
    expect(queryToSql(query)).toBe(generator.query(query));
    expect(SqlString.escapeId("users")).toBe(generator.escapeId("users"));
    expect(formatQuery`SELECT ${true}`).toBe(generator.format`SELECT ${true}`);
  }
  expect(queryToSql(query, mysql)).toBe(mysql.query(query));
});
