import { StoreMigrator } from "../migration/front/storeMigrator.js";
import { QExpr } from "../runtime/dsl/factory.js";
import { createToSql } from "../runtime/dsl/mutation/mutation.js";
import { queryToSql } from "../runtime/dsl/query/sql/queryToSql.js";
import { SqlString } from "../runtime/sql/sqlString.js";
import { withDialect } from "./dialect.js";

const pg = <T>(run: () => T) => withDialect("postgres", run);
const tableInfo = {
  users: {
    identifiableKeys: ["user_id"],
    identifiableFields: ["id"],
    columnMap: { id: "user_id", name: "displayName" },
  },
};

test("scopes dialects independently across concurrent work and nested calls", async () => {
  const result = await Promise.all([
    withDialect("postgres", async () => {
      await Promise.resolve();
      expect(withDialect("mysql", () => SqlString.escapeId("a"))).toBe("`a`");
      return SqlString.escapeId("a");
    }),
    withDialect("mysql", async () => {
      await Promise.resolve();
      return SqlString.escapeId("a");
    }),
  ]);
  expect(result).toEqual(['"a"', "`a`"]);
});

test("escapes PostgreSQL values without MySQL backslash semantics", () => {
  pg(() => {
    expect(SqlString.escape("O'Reilly\\'; DROP TABLE users; --")).toBe(
      "E'O''Reilly\\\\''; DROP TABLE users; --'",
    );
    expect(SqlString.escapeId('schema.Mixed"Case')).toBe(
      '"schema"."Mixed""Case"',
    );
    expect(SqlString.escape(false)).toBe("FALSE");
    expect(SqlString.escape(null)).toBe("NULL");
    expect(() => SqlString.escape("a\0b")).toThrow("NUL");
    expect(() => SqlString.escape(Infinity)).toThrow("finite");
  });
});

test("generates identity, quoted constraints, indexes, alterations and timestamp triggers", () => {
  pg(() => {
    const store = StoreMigrator.deserialize({ tables: [] });
    store.createTable("users", (t) => {
      t.autoIncrementHashId("userId");
      t.column("name").varchar(40).unique();
      t.updatedAt();
      t.addIndex("name");
    });
    const sql = store.getSql().join(";\n");
    expect(sql).toContain('"userId" integer GENERATED BY DEFAULT AS IDENTITY');
    expect(sql).toContain('CHECK ("userId" >= 0)');
    expect(sql).toContain('UNIQUE ("name")');
    expect(sql).toContain('CREATE INDEX "index_users__name"');
    expect(sql).toContain('CREATE TRIGGER "sasat_update_timestamp"');
    expect(sql).not.toMatch(
      /AUTO_INCREMENT|UNSIGNED|ON UPDATE CURRENT_TIMESTAMP/,
    );
    store.resetQueue();
    store
      .table("users")
      .changeColumnType("name", "text")
      .setDefault("name", "guest")
      .removeIndex("name");
    expect(store.getSql()).toEqual([
      'ALTER TABLE "users" ALTER COLUMN "name" TYPE text',
      'ALTER TABLE "users" ALTER "name" SET DEFAULT E\'guest\'',
      'DROP INDEX "index_users__name"',
    ]);
  });
});

test("uses RETURNING, DEFAULT VALUES and explicit PostgreSQL conflict targets", () => {
  pg(() => {
    expect(
      createToSql(
        { table: "users", fields: [], entities: [[]], returning: "user_id" },
        tableInfo,
      ),
    ).toBe(
      'INSERT INTO "users" DEFAULT VALUES RETURNING "user_id" AS "__sasat_insert_id"',
    );
    const sql = createToSql(
      {
        table: "users",
        fields: ["id", "name"],
        entities: [[1, "Ada"]],
        upsert: ["displayName"],
        returning: "user_id",
      },
      tableInfo,
    );
    expect(sql).toContain(
      'ON CONFLICT ("user_id") DO UPDATE SET "displayName" = EXCLUDED."displayName"',
    );
    expect(
      createToSql(
        { table: "users", fields: ["name"], entities: [["Ada"]], ignore: true },
        tableInfo,
      ),
    ).toContain("ON CONFLICT DO NOTHING");
    expect(
      createToSql(
        {
          table: "users",
          fields: ["name"],
          entities: [["Ada"]],
          upsert: ["displayName"],
          conflictColumns: ["displayName"],
        },
        tableInfo,
      ),
    ).toContain('ON CONFLICT ("displayName")');
  });
});

test("quotes SQL aliases and preserves conditions, zero limits and root-only row locks", () => {
  pg(() => {
    const field = QExpr.field("u", "userId");
    const query = {
      select: [field],
      from: QExpr.table("users", [], "u"),
      where: QExpr.eq(field, QExpr.value(1)),
      limit: 0,
      lock: "FOR UPDATE" as const,
    };
    expect(queryToSql(query)).toBe(
      'SELECT "u"."userId" FROM "users" AS "u" WHERE "u"."userId"  = 1 LIMIT 0 FOR UPDATE OF "u"',
    );
  });
});
