import type { Index } from "../migration/data/index.js";
import {
  type Reference,
  referenceToSql,
  type SerializedColumn,
} from "../migration/serialized/serializedColumn.js";
import type { SerializedTable } from "../migration/serialized/serializedStore.js";
import {
  type Create,
  createToSql,
  type Delete,
  deleteToSql,
  type Update,
  updateToSql,
} from "../runtime/dsl/mutation/mutation.js";
import type { TableInfo } from "../runtime/dsl/query/createQueryResolveInfo.js";
import type { Query } from "../runtime/dsl/query/query.js";
import { createSqlNodes } from "../runtime/dsl/query/sql/nodeToSql.js";
import { queryToSql } from "../runtime/dsl/query/sql/queryToSql.js";
import { getSqlString } from "../runtime/sql/sqlString.js";
import type { SQLExecutor } from "./connectors/dbClient.js";
import { type DatabaseDialect, getDialect } from "./dialect.js";
import { formatQueryWith } from "./formatQuery.js";
import { columnToSql } from "./sql/columnToSql.js";
import {
  dropPostgresTimestampFunction,
  postgresTimestampTrigger,
} from "./sql/postgres.js";
import { createSqlCreator } from "./sql/sqlCreater.js";

/** Stateless SQL generation, independent of database drivers and connections. */
export class SqlGenerator {
  readonly escape: (value: unknown) => string;
  readonly escapeId: (name: string) => string;
  readonly nodes: ReturnType<typeof createSqlNodes>;
  readonly alter: ReturnType<typeof createSqlCreator>;

  constructor(readonly dialect: DatabaseDialect) {
    if (dialect !== "mysql" && dialect !== "postgres")
      throw new Error("SQL dialect must be mysql or postgres");
    const strings = getSqlString(dialect);
    this.escape = strings.escape;
    this.escapeId = strings.escapeId;
    this.nodes = createSqlNodes(this);
    this.alter = createSqlCreator(this);
    Object.freeze(this);
  }

  query(query: Query): string {
    return queryToSql(query, this);
  }
  create(dsl: Create, tables: TableInfo): string {
    return createToSql(dsl, tables, this);
  }
  update(dsl: Update, tables: TableInfo): string {
    return updateToSql(dsl, tables, this);
  }
  delete(dsl: Delete): string {
    return deleteToSql(dsl, this);
  }
  column(column: SerializedColumn): string {
    return columnToSql(column, this);
  }
  reference(name: string, reference: Reference): string {
    return referenceToSql(name, reference, this);
  }
  format(str: TemplateStringsArray, ...params: unknown[]): string {
    return formatQueryWith(this, str, ...params);
  }

  createTable(table: SerializedTable): string {
    const rows = table.columns.map((column) => this.column(column));
    if (table.primaryKey.length)
      rows.push(
        `PRIMARY KEY (${table.primaryKey.map(this.escapeId).join(",")})`,
      );
    for (const columns of table.uniqueKeys)
      rows.push(
        this.dialect === "postgres"
          ? `UNIQUE (${columns.map(this.escapeId).join(",")})`
          : `UNIQUE KEY (${columns.join(",")})`,
      );
    for (const column of table.columns) {
      if (column.hasReference && !column.reference.noFKey) {
        const ref = column.reference;
        rows.push(
          this.reference(
            `ref_${table.tableName}_${column.fieldName}__${ref.parentTable}_${ref.parentColumn}`,
            ref,
          ),
        );
      }
    }
    return `CREATE TABLE ${this.escapeId(table.tableName)}(${rows.join(", ")})`;
  }

  addIndex(table: string, index: Index): string {
    return this.dialect === "postgres"
      ? `CREATE INDEX ${this.escapeId(index.constraintName)} ON ${this.escapeId(table)} (${index.columns.map(this.escapeId).join(",")})`
      : `ALTER TABLE ${table} ADD INDEX ${index.constraintName}(${index.columns.join(",")})`;
  }
  dropIndex(table: string, index: Index): string {
    return this.dialect === "postgres"
      ? `DROP INDEX ${this.escapeId(index.constraintName)}`
      : `DROP INDEX ${index.constraintName} ON ${table}`;
  }
  dropTable(table: string): string[] {
    return this.dialect === "postgres"
      ? [
          `DROP TABLE ${this.escapeId(table)}`,
          dropPostgresTimestampFunction(table),
        ]
      : [`DROP TABLE ${table}`];
  }
  timestamps(table: SerializedTable): string[] {
    return this.dialect === "postgres" ? postgresTimestampTrigger(table) : [];
  }
  refreshTimestamps(table: SerializedTable): string[] {
    return this.dialect === "postgres"
      ? [
          `DROP TRIGGER IF EXISTS "sasat_update_timestamp" ON ${this.escapeId(table.tableName)}`,
          dropPostgresTimestampFunction(table.tableName),
          ...this.timestamps(table),
        ]
      : [];
  }
  migrationTable(name: string): string {
    const table = this.escapeId(name);
    return this.dialect === "postgres"
      ? `CREATE TABLE IF NOT EXISTS ${table} (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(100) NOT NULL, direction varchar(4) NOT NULL CHECK (direction IN ('up', 'down')), migrated_at timestamp DEFAULT CURRENT_TIMESTAMP)`
      : `CREATE TABLE IF NOT EXISTS ${table} ` +
          "(id int auto_increment primary key , name varchar(100) not null," +
          "direction enum('up', 'down') not null, migrated_at timestamp default current_timestamp)";
  }
}

const generators = new Map<DatabaseDialect, SqlGenerator>();
/** Configuration is read only when the caller omits a dialect. */
export function createSqlGenerator(
  dialect: DatabaseDialect = getDialect(),
): SqlGenerator {
  let generator = generators.get(dialect);
  if (!generator) {
    generator = new SqlGenerator(dialect);
    generators.set(dialect, generator);
  }
  return generator;
}

/** Compatibility boundary for custom executors that predate SQL generators. */
export function sqlFor(
  executor: Pick<SQLExecutor, "sql" | "dialect">,
): SqlGenerator {
  return executor.sql ?? createSqlGenerator(executor.dialect);
}
