import assert from "node:assert/strict";
import type { SQLExecutor } from "../../src/db/connectors/dbClient.js";
import type { DatabaseDialect } from "../../src/db/dialect.js";
import { createSqlGenerator } from "../../src/db/sqlGenerator.js";
import { SasatDBDatasource } from "../../src/runtime/sasatDBDatasource.js";

type Row = { id: number; name: string; note: string | null };
type Input = { id?: number; name?: string; note?: string | null };
class BulkRows extends SasatDBDatasource<
  Row,
  { id: number },
  Input,
  { id: number; note?: string | null },
  { fields: (keyof Row)[] },
  Row
> {
  tableName = "bulk_rows";
  fields = ["id", "name", "note"];
  primaryKeys = ["id"];
  identifyFields = ["id"];
  autoIncrementColumn = "id";
  relationMap = { bulk_rows: {} };
  tableInfo = {
    bulk_rows: {
      identifiableKeys: ["id"],
      identifiableFields: ["id"],
      columnMap: { id: "id", name: "name", note: "stored_note" },
    },
  };
  getDefaultValueString() {
    return {};
  }
}

/** Both callers supply their existing isolated test database. */
export async function verifyBulkInsert(
  executor: SQLExecutor,
  dialect: DatabaseDialect,
) {
  const sql = createSqlGenerator(dialect);
  const q = sql.escapeId;
  let statements = 0;
  const rows = new BulkRows({
    sql,
    rawQuery: (query) => executor.rawQuery(query),
    rawCommand: (query) => {
      statements++;
      return executor.rawCommand(query);
    },
  });
  await executor.rawQuery(
    `CREATE TABLE ${q("bulk_rows")} (id ${dialect === "mysql" ? "int AUTO_INCREMENT" : "integer GENERATED BY DEFAULT AS IDENTITY"} PRIMARY KEY, name varchar(50) DEFAULT 'db-name', stored_note varchar(100) DEFAULT 'db-note')${dialect === "mysql" ? " ENGINE=InnoDB" : ""}`,
  );
  try {
    const input: Input[] = [
      { id: 10, name: "a" },
      { id: 20, name: "b", note: "kept" },
      { id: 30, name: "c", note: null },
      { id: 40, name: "d", note: undefined },
    ];
    for (const batch of [input, [...input].reverse()]) {
      await executor.rawQuery(`DELETE FROM ${q("bulk_rows")}`);
      const before = statements;
      const result = await rows.createBulk(batch);
      assert.equal(statements, before + 1);
      assert.equal(result?.affectedRows, 4);
      assert.deepEqual(
        await executor.rawQuery(
          `SELECT id, name, stored_note FROM ${q("bulk_rows")} ORDER BY id`,
        ),
        [
          { id: 10, name: "a", stored_note: "db-note" },
          { id: 20, name: "b", stored_note: "kept" },
          { id: 30, name: "c", stored_note: null },
          { id: 40, name: "d", stored_note: "db-note" },
        ],
      );
    }
    assert.equal(
      (
        await rows.createBulk(
          [
            { id: 10, note: "ignored" },
            { id: 50, note: "new" },
          ],
          { ignore: true },
        )
      )?.affectedRows,
      1,
    );
    await rows.createBulk([{ id: 10 }, { id: 20, note: "updated" }], {
      upsert: { updateColumns: ["stored_note"], conflictColumns: ["id"] },
    });
    assert.deepEqual(
      await executor.rawQuery(
        `SELECT stored_note FROM ${q("bulk_rows")} WHERE id IN (10,20) ORDER BY id`,
      ),
      [{ stored_note: "db-note" }, { stored_note: "updated" }],
    );
    await assert.rejects(
      rows.createBulk([
        { id: 99999, note: "must-rollback" },
        { id: 10, note: "duplicate" },
      ]),
    );
    assert.equal(
      (
        await executor.rawQuery(
          `SELECT id FROM ${q("bulk_rows")} WHERE id=99999`,
        )
      ).length,
      0,
    );
    const beforeEmpty = statements;
    assert.equal(await rows.createBulk([]), null);
    assert.equal(statements, beforeEmpty);
    assert.equal((await rows.createBulk([{}, {}]))?.affectedRows, 2);
    const beforeLarge = statements;
    assert.equal(
      (
        await rows.createBulk(
          Array.from({ length: 1000 }, (_, i) => ({
            id: 200000 + i,
            ...(i % 2 ? { note: "kept" } : {}),
          })),
        )
      )?.affectedRows,
      1000,
    );
    assert.equal(statements, beforeLarge + 1);
    assert.equal(
      (
        await executor.rawQuery(
          `SELECT id FROM ${q("bulk_rows")} WHERE stored_note='kept' AND id>=200000`,
        )
      ).length,
      500,
    );
  } finally {
    await executor.rawQuery(`DROP TABLE ${q("bulk_rows")}`);
  }
}
