import assert from "node:assert/strict";
import type {
  DBClient,
  SQLExecutor,
} from "../../src/db/connectors/dbClient.js";
import type { SqlStatement } from "../../src/db/sqlStatement.js";
import { QExpr as q } from "../../src/runtime/dsl/factory.js";
import { SasatDBDatasource } from "../../src/runtime/sasatDBDatasource.js";

type Row = {
  id: bigint;
  name: string;
  price: string;
  note: string | null;
  tenant: number;
};
type Input = Partial<Row>;
class WriteRows extends SasatDBDatasource<
  Row,
  { id: bigint },
  Input,
  Input & { id: bigint },
  { fields: (keyof Row)[] },
  Row
> {
  tableName = "prepared_writes";
  fields = ["id", "name", "price", "note", "tenant"];
  primaryKeys = ["row_id"];
  identifyFields = ["id"];
  autoIncrementColumn = "id";
  override autoIncrementBigInt = true;
  relationMap = { prepared_writes: {} };
  tableInfo = {
    prepared_writes: {
      identifiableKeys: ["row_id"],
      identifiableFields: ["id"],
      columnMap: {
        id: "row_id",
        name: "display_name",
        price: "price",
        note: "stored_note",
        tenant: "tenant_id",
      },
    },
  };
  getDefaultValueString() {
    return {};
  }
}

/** Uses only the caller's isolated test database. */
export async function verifyCompiledMutations(client: DBClient) {
  const postgres = client.dialect === "postgres";
  const firstId = 9007199254740993n;
  await client.rawCommand(
    `CREATE TABLE prepared_writes (row_id ${postgres ? "BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 9007199254740993)" : "BIGINT AUTO_INCREMENT"} PRIMARY KEY, display_name VARCHAR(100) UNIQUE, price DECIMAL(38,18) DEFAULT 1.0, stored_note VARCHAR(100) DEFAULT 'db-note', tenant_id INTEGER DEFAULT 42)${postgres ? "" : " ENGINE=InnoDB AUTO_INCREMENT=9007199254740993"}`,
  );
  await client.rawCommand(
    "CREATE TABLE prepared_scope (allowed_id BIGINT PRIMARY KEY, tenant_id INTEGER)",
  );
  const commands: SqlStatement[] = [];
  const executor: SQLExecutor = {
    sql: client.sql,
    supportsParameterizedStatements: true,
    executeQuery: (statement) => client.executeQuery(statement),
    executeCommand: (statement) => {
      commands.push(statement);
      return client.executeCommand(statement);
    },
    rawQuery: (text) => client.rawQuery(text),
    rawCommand: async () => {
      throw new Error("Unexpected raw mutation");
    },
  };
  const rows = new WriteRows(executor);
  const find = (id: bigint) =>
    rows.first(undefined, {
      where: q.eq(q.field("t0", "row_id"), q.value(id)),
    });
  try {
    const name = "O'Reilly\\日本語 ? $1 --";
    const price = "12345678901234567890.123456789012345678";
    const row = await rows.create({ name, price, tenant: 42 });
    assert.equal(row.id, firstId);
    assert.equal((await find(firstId))?.price, price);
    assert.equal((await find(firstId))?.name, name);
    assert.equal((await find(firstId))?.note, "db-note");
    assert.ok(!commands[0].text.includes(name));
    assert.ok(commands[0].values.includes(name));
    await rows.update({
      id: firstId,
      note: null,
      price: "-0.000000000000000001",
      name: undefined,
    });
    assert.equal((await find(firstId))?.name, name);
    assert.equal((await find(firstId))?.note, null);
    assert.equal((await find(firstId))?.price, "-0.000000000000000001");
    const denied = await rows.updateWhere(
      { note: "denied" },
      q.and(
        q.eq(q.field("prepared_writes", "row_id"), q.value(firstId)),
        q.eq(q.field("prepared_writes", "tenant_id"), q.value(99)),
      ),
    );
    assert.equal(denied.affectedRows, 0);
    assert.equal((await find(firstId))?.note, null);
    const batch = [
      { id: firstId + 10n, name: "bulk-a", price, note: null },
      { id: firstId + 11n, name: "bulk-b", note: undefined },
    ];
    assert.equal((await rows.createBulk(batch))?.affectedRows, 2);
    assert.equal((await find(firstId + 10n))?.note, null);
    assert.equal((await find(firstId + 11n))?.note, "db-note");
    assert.equal((await find(firstId + 11n))?.price, "1.000000000000000000");
    await rows.upsert(
      { name: "bulk-a", price: "2.000000000000000001" },
      ["price"],
      ["name"],
    );
    assert.equal((await find(firstId + 10n))?.price, "2.000000000000000001");
    await rows.createBulk(
      [{ id: firstId + 10n }, { id: firstId + 11n, note: "updated" }],
      {
        upsert: { updateColumns: ["stored_note"], conflictColumns: ["row_id"] },
      },
    );
    assert.equal((await find(firstId + 10n))?.note, "db-note");
    assert.equal((await find(firstId + 11n))?.note, "updated");
    assert.equal(
      (
        await rows.createBulk(
          [
            { id: firstId + 10n, note: "ignored" },
            { id: firstId + 12n, name: "bulk-c" },
          ],
          { ignore: true },
        )
      )?.affectedRows,
      1,
    );
    assert.equal((await find(firstId + 10n))?.note, "db-note");
    const attempts = commands.length;
    await assert.rejects(
      rows.createBulk([
        { id: firstId + 1000n, name: "must-rollback" },
        { id: firstId + 10n, name: "duplicate" },
      ]),
    );
    assert.equal(commands.length, attempts + 1, "failed bulk is never retried");
    assert.equal(await find(firstId + 1000n), null);
    const tx = await client.transaction();
    try {
      const txRows = new WriteRows(tx);
      await txRows.create({ id: firstId + 1001n, name: "tx-rollback" });
      await assert.rejects(
        txRows.create({ id: firstId, name: "tx-duplicate" }),
      );
    } finally {
      await tx.rollback();
    }
    assert.equal(await find(firstId + 1001n), null);
    const committed = await client.transaction();
    try {
      const txRows = new WriteRows(committed);
      await txRows.create({ id: firstId + 1002n, name: "tx-commit" });
      await txRows.update({ id: firstId + 1002n, note: null });
      await committed.commit();
    } catch (error) {
      await committed.rollback();
      throw error;
    }
    assert.equal((await find(firstId + 1002n))?.note, null);
    const parallel = await Promise.all([
      rows.create({ name: "parallel-a" }),
      rows.create({ name: "parallel-b" }),
    ]);
    assert.deepEqual(
      (await Promise.all(parallel.map((row) => find(row.id)))).map(
        (row) => row?.name,
      ),
      ["parallel-a", "parallel-b"],
    );
    await client.rawCommand(
      `INSERT INTO prepared_scope VALUES (${firstId},42)`,
    );
    const allowed = {
      select: [q.field("s", "allowed_id")],
      from: q.table("prepared_scope", [], "s"),
      where: q.eq(q.field("s", "tenant_id"), q.value(42)),
    };
    const condition = q.in(q.field("prepared_writes", "row_id"), allowed);
    assert.equal(
      (await rows.updateWhere({ note: "allowed" }, condition)).affectedRows,
      1,
    );
    assert.equal((await find(firstId))?.note, "allowed");
    assert.equal((await rows.deleteWhere(condition)).affectedRows, 1);
    assert.equal(await find(firstId), null);
    assert.equal((await rows.delete({ id: firstId + 10n })).affectedRows, 1);
    assert.equal(await find(firstId + 10n), null);
  } finally {
    await client.rawCommand("DROP TABLE prepared_scope");
    await client.rawCommand("DROP TABLE prepared_writes");
  }
}
